name: Lint & Format
on: [push, pull_request]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: uv pip install --system flake8 black isort pytest
      - run: bash scripts/checks.sh
