name: Test Suite
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.11'
      - run: uv pip install --system pytest coverage
      - run: |
          coverage run -m pytest -q
          coverage xml
      - uses: codecov/codecov-action@v5
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
