name: Docs Preview & Link Check
on:
  push:
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          uv pip install --system linkchecker
          linkchecker README.md docs/ || true
