name: Build STL
on:
  push:
    paths:
      - 'hardware/scad/**/*.scad'
      - 'hardware/inputs/**/*.json'
  workflow_dispatch:

jobs:
  build-stl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install OpenSCAD
        run: sudo apt-get update && sudo apt-get install -y openscad
      - name: Render SCAD files
        run: infra/ci/stl_regression.py
      - name: Commit STL models
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add hardware/stl/**/*.stl hardware/stl/checksums.sha256 || true
          if git diff --cached --quiet; then
            echo "No STL changes to commit"
          else
            git commit -m "chore: update STL models"
            git push
          fi
